name: Up to Date

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Install Dependencies
        run: yarn

      - name: Generate Cheat Sheet
        run: yarn generate

      - name: Push New Cheat Sheet to Updated Branch
        run: |
          git diff --name-only --exit-code && exit 0
          git add README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "docs(readme): update emoji-cheat-sheet"
          git push -qf "https://${{ secrets.GITHUB_TOKEN }}@github.com/ikatyang/emoji-cheat-sheet.git" HEAD:github-actions-auto-update

      - name: Create PR from Updated Branch
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {owner, repo} = context.repo
            const branch = 'github-actions-auto-update'
            const {status: branchStatus} = await github.repos.getBranch({
              owner,
              repo,
              branch,
            })
            if (branchStatus !== 200) {
              return
            }
            const {status, data: prs} = await github.pulls.list({
              owner,
              repo,
              head: branch,
              state: 'open',
            })
            if (status === 200 && prs.length === 0) {
              await github.pulls.create({
                owner,
                repo,
                head: branch,
                title: 'docs(readme): update emoji-cheat-sheet',
                base: 'master',
              })
            }
